//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YT_CAD_TOOL.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public string t_min {
            get {
                return ((string)(this["t_min"]));
            }
            set {
                this["t_min"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public string t_max {
            get {
                return ((string)(this["t_max"]));
            }
            set {
                this["t_max"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool c_top {
            get {
                return ((bool)(this["c_top"]));
            }
            set {
                this["c_top"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool c_top2 {
            get {
                return ((bool)(this["c_top2"]));
            }
            set {
                this["c_top2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public string t_size {
            get {
                return ((string)(this["t_size"]));
            }
            set {
                this["t_size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public string t_extend {
            get {
                return ((string)(this["t_extend"]));
            }
            set {
                this["t_extend"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public string t_distance {
            get {
                return ((string)(this["t_distance"]));
            }
            set {
                this["t_distance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string t_distance2 {
            get {
                return ((string)(this["t_distance2"]));
            }
            set {
                this["t_distance2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("없음")]
        public string layer01 {
            get {
                return ((string)(this["layer01"]));
            }
            set {
                this["layer01"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("없음")]
        public string layer02 {
            get {
                return ((string)(this["layer02"]));
            }
            set {
                this["layer02"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("없음")]
        public string layer03 {
            get {
                return ((string)(this["layer03"]));
            }
            set {
                this["layer03"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("없음")]
        public string layer04 {
            get {
                return ((string)(this["layer04"]));
            }
            set {
                this["layer04"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection layers01 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["layers01"]));
            }
            set {
                this["layers01"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection layers02 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["layers02"]));
            }
            set {
                this["layers02"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection layers03 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["layers03"]));
            }
            set {
                this["layers03"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection layers04 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["layers04"]));
            }
            set {
                this["layers04"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection layers05 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["layers05"]));
            }
            set {
                this["layers05"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool c_top3 {
            get {
                return ((bool)(this["c_top3"]));
            }
            set {
                this["c_top3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection saveNames {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["saveNames"]));
            }
            set {
                this["saveNames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection saveData1 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["saveData1"]));
            }
            set {
                this["saveData1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection saveData2 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["saveData2"]));
            }
            set {
                this["saveData2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection saveData3 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["saveData3"]));
            }
            set {
                this["saveData3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection saveData4 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["saveData4"]));
            }
            set {
                this["saveData4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection saveData5 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["saveData5"]));
            }
            set {
                this["saveData5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool c_top4 {
            get {
                return ((bool)(this["c_top4"]));
            }
            set {
                this["c_top4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public string t_AD {
            get {
                return ((string)(this["t_AD"]));
            }
            set {
                this["t_AD"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.0.253\\SQLEXPRESS,1433;Initial Catalog=HDC.SPEC;User ID=abies;" +
            "Password=YT!DEV!0527;Connect Timeout=30;Encrypt=False;TrustServerCertificate=Fal" +
            "se")]
        public string HDC_SPECConnectionString {
            get {
                return ((string)(this["HDC_SPECConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.0.253\\SQLEXPRESS,1433;Initial Catalog=HDC.SPEC;User ID=abies;" +
            "Connect Timeout=30;Encrypt=False;TrustServerCertificate=False")]
        public string HDC_SPECConnectionString1 {
            get {
                return ((string)(this["HDC_SPECConnectionString1"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection layers06 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["layers06"]));
            }
            set {
                this["layers06"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection layers07 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["layers07"]));
            }
            set {
                this["layers07"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection layers08 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["layers08"]));
            }
            set {
                this["layers08"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection layers09 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["layers09"]));
            }
            set {
                this["layers09"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection layers10 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["layers10"]));
            }
            set {
                this["layers10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection saveData6 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["saveData6"]));
            }
            set {
                this["saveData6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection saveData7 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["saveData7"]));
            }
            set {
                this["saveData7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection saveData8 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["saveData8"]));
            }
            set {
                this["saveData8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection saveData9 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["saveData9"]));
            }
            set {
                this["saveData9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection saveData10 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["saveData10"]));
            }
            set {
                this["saveData10"] = value;
            }
        }
    }
}
